language: ruby
rvm:
  - 1.9.3
  - 2.1.0
  - jruby-19mode
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm:
      - 1.9.3
      - jruby-19mode
addons:
  code_climate:
    repo_token: 197d6b3eb448e97f94a63414e2f6b6a96d0bf0d44514cf57100be14483302d12
